name: deeprank-gnn-esm-gpu
channels:
  - pytorch
  - pyg
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - biopython=1.78
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.15
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=2.8.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.25.0
  - numpy-base=1.25.0
  - openssl=3.0.9
  - packaging=23.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.1.2
  - ply=3.11
  - pooch=1.4.0
  - psutil=5.9.0
  - pycparser=2.21
  - pyg=2.3.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-louvain=0.15
  - pytorch=2.0.1
  - pytorch-cluster=1.6.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - pytorch-spline-conv=1.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchtriton=2.0.0
  - tornado=6.2
  - tqdm=4.65.0
  - typing_extensions=4.6.3
  - urllib3=1.26.16
  - wheel=0.38.4
  - xz=5.4.2
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - chart-studio==1.1.0
      - exceptiongroup==1.1.1
      - freesasa==2.2.0.post3
      - iniconfig==2.0.0
      - markov-clustering==0.0.6.dev0
      - pandas==2.0.2
      - pdb2sql==0.5.3
      - plotly==5.15.0
      - pluggy==1.2.0
      - pytest==7.4.0
      - pytz==2023.3
      - retrying==1.3.4
      - tenacity==8.2.2
      - tomli==2.0.1
      - tzdata==2023.3
